const SET_USER_INFOR = "SET_USER_INFOR"
const SET_TITLE_HEADER = "SET_TITLE_HEADER"
const SET_DETAIL_DAYOFF = "SET_DETAIL_DAYOFF"
const SET_TOGGLE_DARK_LIGHT = "SET_TOGGLE_DARK_LIGHT"

export { SET_USER_INFOR, SET_TITLE_HEADER, SET_DETAIL_DAYOFF,SET_TOGGLE_DARK_LIGHT };